# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: $(build.sourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  - group: azch-docker
  - name: imageName
    value: '$(dockerId)/frontend'
  - name: dockerRegistryServiceConnection
    value: 'containerRegistryConnection' 

steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: azch-frontend
      dockerfile: '**/Dockerfile'
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: $(tag)

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'manifests'
      targetPath: 'manifests'